name: user_repository
description: "The repo that handles users"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
